#!/bin/bash
# Writes Python service .env with CORS_ORIGINS (frontend + backend URLs, comma-separated).

set -euo pipefail

DEFAULT_HOST="localhost"
DEFAULT_FRONTEND_PORT=3737
DEFAULT_BACKEND_PORT=7331

read -p "Host [${DEFAULT_HOST}]: " HOST
HOST=${HOST:-$DEFAULT_HOST}

read -p "Frontend port [${DEFAULT_FRONTEND_PORT}]: " FP
FP=${FP:-$DEFAULT_FRONTEND_PORT}

read -p "Backend port [${DEFAULT_BACKEND_PORT}]: " BP
BP=${BP:-$DEFAULT_BACKEND_PORT}

FRONTEND_URL="http://${HOST}:${FP}"
BACKEND_URL="http://${HOST}:${BP}"
CORS_ORIGINS="${FRONTEND_URL},${BACKEND_URL}"

cat > .env << EOF
# Generated by setup-env.sh — do not commit (.gitignore)
CORS_ORIGINS=${CORS_ORIGINS}
EOF

echo "Wrote .env with CORS_ORIGINS. Restart uvicorn after changes."
