#!/bin/bash
# Writes Python service .env (CORS_ORIGINS for browser or Spring when calling with Origin).

set -euo pipefail

DEFAULT_HOST="localhost"
DEFAULT_FRONTEND_PORT=3737
DEFAULT_BACKEND_PORT=7331

read -p "Host used in dev URLs [${DEFAULT_HOST}]: " HOST
HOST=${HOST:-$DEFAULT_HOST}

read -p "Frontend port [${DEFAULT_FRONTEND_PORT}]: " FP
FP=${FP:-$DEFAULT_FRONTEND_PORT}

read -p "Spring API port (gateway) [${DEFAULT_BACKEND_PORT}]: " BP
BP=${BP:-$DEFAULT_BACKEND_PORT}

FRONTEND_URL="http://${HOST}:${FP}"
BACKEND_URL="http://${HOST}:${BP}"
# Match common browser Origin variants for local dev (regex in app also covers loopback any-port when enabled).
CORS_ORIGINS="${FRONTEND_URL},${BACKEND_URL},http://127.0.0.1:${FP},http://127.0.0.1:${BP},http://localhost:${FP},http://localhost:${BP}"

cat > .env << EOF
# Generated by setup-env.sh — do not commit (.gitignore)
CORS_ORIGINS=${CORS_ORIGINS}
EOF

echo "Wrote .env with CORS_ORIGINS. Restart uvicorn after changes."
